#!/usr/bin/env python3
"""build_standalone.py — assemble khipu-3d.html (single-file failsafe).

Inlines theme.css + formulas.js + data-adapter.js + khipu-3d.js into one HTML
file the founder can open locally or drop on ANY host. CDN deps (three.js +
3d-force-graph + three-spritetext) stay as <script src> so the file is small;
the data points at the public organ Spaces, so it runs from anywhere.

Signed-off-by: Yachay <yachay@szlholdings.ai>
Co-Authored-By: Perplexity Computer Agent <agent@perplexity.ai>
"""
import os

HERE = os.path.dirname(os.path.abspath(__file__))


def read(name: str) -> str:
    with open(os.path.join(HERE, name), encoding="utf-8") as f:
        return f.read()


def main() -> None:
    css = read("theme.css")
    formulas = read("formulas.js")
    adapter = read("data-adapter.js")
    main_js = read("khipu-3d.js")
    index = read("index.html")

    # Replace external <link rel=stylesheet href=theme.css> with inline <style>.
    index = index.replace(
        '<link rel="stylesheet" href="theme.css" />',
        f"<style>\n{css}\n</style>",
    )
    # Replace the three local <script src> tags with inline blocks.
    inline_scripts = (
        f'<script>\n{formulas}\n</script>\n'
        f'<script>\n{adapter}\n</script>\n'
        f'<script>\n{main_js}\n</script>'
    )
    index = index.replace(
        '<script src="formulas.js"></script>\n'
        '  <script src="data-adapter.js"></script>\n'
        '  <script src="khipu-3d.js"></script>',
        inline_scripts,
    )
    banner = (
        "<!-- ======================================================================\n"
        "  STANDALONE single-file Khipu 3D (Beat 3) — generated by build_standalone.py\n"
        "  Open locally or drop on any host. Failsafe if the HF Space is BUILD_ERROR.\n"
        "  Live data from the public organ Spaces. Honesty over checklist.\n"
        "  Signed-off-by: Yachay <yachay@szlholdings.ai>\n"
        "  Co-Authored-By: Perplexity Computer Agent <agent@perplexity.ai>\n"
        "====================================================================== -->\n"
    )
    out = banner + index
    with open(os.path.join(HERE, "khipu-3d.html"), "w", encoding="utf-8") as f:
        f.write(out)
    print(f"wrote khipu-3d.html ({len(out)} bytes)")


if __name__ == "__main__":
    main()
