apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "rosie-api.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "rosie-api.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.pdb.minAvailable }}
  selector:
    matchLabels:
      {{- include "rosie-api.selectorLabels" . | nindent 6 }}
