{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "rosie-api.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "rosie-api.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "rosie-api.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      path: {{ .Values.serviceMonitor.path }}
      interval: {{ .Values.serviceMonitor.interval }}
{{- end }}
